version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    
    steps:
      - checkout
      - run:
          name: Install Node
          command: curl -fsSL https://deb.nodesource.com/setup_15.x | sudo -E bash - && sudo apt-get install -y nodejs     
      - run:
          name: Install Yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Download Dependencies
          command: cd ./example/android/ && sudo chmod +x ./gradlew && ./gradlew androidDependencies
      - run:
          name: Build
          command: cd ./example/android/ && sudo chmod +x ./gradlew && ./gradlew build
